### ISSUE TITLE
是不是该兼容agp7.4了

### ISSUE THREAD

**Issue by zwonb** [kanyun-inc/Kace#16]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib:compileAWenzhouDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by RicardoJiang** [comment]
我们这边处理下

**Comment by bennyhuo** [comment]
确定不是 Kotlin 编译失败了？

**Comment by RicardoJiang** [comment]
是agp7.4 中添加srcDir的api又变了，导致生成的代码没有添加到srcDir中，导致编译不过

**Comment by RicardoJiang** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':lib:compileAWenzhouDebugKotlin'.
> 
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> > Compilation error. See log for more details

最新版本1.7.0-1.0.3-SNAPSHOT已兼容agp7.4.0，可升级试试
