### ISSUE TITLE
能把 id 生成驼峰样式的吗？

### ISSUE THREAD

**Issue by zsqw123** [kanyun-inc/Kace#2]
众所周知，ViewBinding 是会把下划线的改成驼峰样式，这曾经是我喜欢 ViewBinding 的唯一一个原因。

应该是能做到的，希望能加个参数做开关。我希望这个框架不止是为了迁移 1.8 这一个理由而做，而是能做的更好。Google 推的 VB 我觉得是一坨屎，我不看好

**Comment by RicardoJiang** [comment]
可以做，但似乎没有必要。这个框架的目的还是为了帮助开发者迁移KAE，而不是代替ViewBinding。

**Comment by bennyhuo** [comment]
正如 @RicardoJiang 提到的，我们开源 Kace 的目的是**迁移**。内部讨论方案的时候我们确实想过为 Kace 的后端添加 ViewBinding 的实现，但这样反而违背了**迁移**这个初衷。

Kae 尽管用起来方便，但问题也很多，各方已经有过非常多的讨论和验证，这也是我们迁移 ViewBinding 的原因。ViewBinding 限定了作用范围使得对 View 的访问更加安全，尽管用起来不如 Kae 那么简便，但所谓有得有失吧。

如果您希望将 id 生成驼峰的方式，目前建议 fork 代码自行修改。

issue 我先关闭了，如果需要继续讨论，欢迎再次将其打开。

谢谢关注和支持。
