### ISSUE TITLE
Support Generic View Type

### ISSUE THREAD

**Issue by bennyhuo** [kanyun-inc/Kace#24]
Generated files from layout contains generic view type cannot compile.

![image](https://user-images.githubusercontent.com/6336960/217134042-631a4d5f-559f-486f-b4ff-4550c6bfd332.png)

The type of pickerView is `UIKitOptionsExtPickerView<T>`. 

Consider generating Java source code to avoid the generic arguments by taking advance of the Java raw type.

**Comment by jarvan11** [comment]
![企业微信截图_1691995248830](https://github.com/kanyun-inc/Kace/assets/17917973/38d88969-6554-48f4-85d8-adbb37332542)
Error:One type argument expected for class BannerViewPager<T : Any!>
泛型报错，不支持这种么？

**Comment by RicardoJiang** [comment]
> ![企业微信截图_1691995248830](https://user-images.githubusercontent.com/17917973/260375946-38d88969-6554-48f4-85d8-adbb37332542.png) Error:One type argument expected for class BannerViewPager<T : Any!> 泛型报错，不支持这种么？

是的，还不支持泛型类型，可以先把这种 layout 加入 blackList 不生成代码，这部分 layout 手动迁移到 findViewById 或者 ViewBinding

**Comment by bennyhuo** [comment]
试一下 1.8.20-1.2.0。

**Comment by jarvan11** [comment]
> 1.8.20-1.2.0-SNAPSHOT
@bennyhuo Could not find com.kanyun.kace:kace-gradle-plugin:1.8.20-1.2.0-SNAPSHOT.
![企业微信截图_16922444726469](https://github.com/kanyun-inc/Kace/assets/17917973/f846c3e7-7be9-42c9-9246-40330a1aab49)

**Comment by RicardoJiang** [comment]
> > 1.8.20-1.2.0-SNAPSHOT
> > @bennyhuo Could not find com.kanyun.kace:kace-gradle-plugin:1.8.20-1.2.0-SNAPSHOT.
> > ![企业微信截图_16922444726469](https://user-images.githubusercontent.com/17917973/261193306-f846c3e7-7be9-42c9-9246-40330a1aab49.png)

snapshot 依赖需要添加如下 maven 仓库地址：
maven { url "https://s01.oss.sonatype.org/content/repositories/snapshots" }

**Comment by jarvan11** [comment]
> 1.8.20-1.2.0-SNAPSHOT
@bennyhuo @RicardoJiang 加了也不行，没看到1.8.20-1.2.0相关的。
https://s01.oss.sonatype.org/content/repositories/snapshots/com/kanyun/kace/kace-gradle-plugin/
![企业微信截图_16922511704975](https://github.com/kanyun-inc/Kace/assets/17917973/f4697e9b-2274-4e57-a70b-9e6cdf7ccea9)

**Comment by RicardoKanYun** [comment]
> > 1.8.20-1.2.0-SNAPSHOT
> > @bennyhuo @RicardoJiang 加了也不行，没看到1.8.20-1.2.0相关的。
> > https://s01.oss.sonatype.org/content/repositories/snapshots/com/kanyun/kace/kace-gradle-plugin/
> > ![企业微信截图_16922511704975](https://user-images.githubusercontent.com/17917973/261209934-f4697e9b-2274-4e57-a70b-9e6cdf7ccea9.png)

现在好了，再看看

**Comment by jarvan11** [comment]
> ![企业微信截图_1691995248830](https://user-images.githubusercontent.com/17917973/260375946-38d88969-6554-48f4-85d8-adbb37332542.png) Error:One type argument expected for class BannerViewPager<T : Any!> 泛型报错，不支持这种么？

@bennyhuo @RicardoKanYun 接入1.8.20-1.2.0-SNAPSHOT，还有这个地方的泛型报错，
error：One type argument expected for class BannerViewPager<T : Any!>
![企业微信截图_16922569385241](https://github.com/kanyun-inc/Kace/assets/17917973/a8f3c09b-93a1-4964-9070-b822415ade18)

**Comment by bennyhuo** [comment]
删掉之前生成的代码试试看，重新生成的代码不长这样了

**Comment by bennyhuo** [comment]
稍等，我 Fix 一下

**Comment by bennyhuo** [comment]
已经更新，再编译一下试试，版本号不变

**Comment by jarvan11** [comment]
> 已经更新，再编译一下试试，版本号不变

@bennyhuo 更新编译了，还是不行
![企业微信截图_16922616352552](https://github.com/kanyun-inc/Kace/assets/17917973/271b0bd6-d196-46ba-9045-819056992b12)
附BannerViewPager三方库类：
![企业微信截图_16922616994408](https://github.com/kanyun-inc/Kace/assets/17917973/45a052d4-e7c8-4d22-8238-6f68ba463b83)

**Comment by bennyhuo** [comment]
看样子你没有拉到最新的包，编译生成的代码应该是这样：

<img width="1061" alt="image" src="https://github.com/kanyun-inc/Kace/assets/6336960/9d8cf81f-7785-4d10-8f65-20024e9ce880">

KaceViewUtils 是这次提交新加的

**Comment by jarvan11** [comment]
> 看样子你没有拉到最新的包，编译生成的代码应该是这样：
> 
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/6336960/261251420-9d8cf81f-7785-4d10-8f65-20024e9ce880.png">
> KaceViewUtils 是这次提交新加的

嗯，可以了，SNAPSHOT版本不能实时更新问题，设置下SNAPSHOT依赖gradle默认缓存时间就好了。
但是KaceViewUtils没找到（Unresolved reference: KaceViewUtils）？
![企业微信截图_16922631916644](https://github.com/kanyun-inc/Kace/assets/17917973/ab83b063-4d92-4ade-9d2a-65106edc3216)

**Comment by bennyhuo** [comment]
kace-runtime 也需要清一下缓存的

**Comment by bennyhuo** [comment]
没有问题的话我准备直接发正式版了。有问题可以随时把 issue 打开。
