### ISSUE TITLE
小建议：关于部分包名中含kotlin关键字所导致的异常

### ISSUE THREAD

**Issue by Petterpx** [kanyun-inc/Kace#29]
生成扩展属性时，有些View对应的包名是 in.com.xx、此时生成的扩展属性 findViewByIdCached<in.com.xx> 就会报错，可以考虑对于包名是kotlin关键字的增加 ``

**Comment by RicardoJiang** [comment]
Kotlin 的关键字还挺多的，如果每个 xml 的 tag 都需要判断一下包名是否包含这些关键字，对生成代码的性能还是有一定影响。最好还是避免使用这些关键字作为包名吧，或者将这些生成有问题的 layout 加入 blackList，禁止生成代码，手动迁移。

**Comment by Petterpx** [comment]
> Kotlin 的关键字还挺多的，如果每个 xml 的 tag 都需要判断一下包名是否包含这些关键字，对生成代码的性能还是有一定影响。最好还是避免使用这些关键字作为包名吧，或者将这些生成有问题的 layout 加入 blackList，禁止生成代码，手动迁移。

项目本身的问题还好说，主要是某些三方库使用了，这就比较痛苦:(...

**Comment by RicardoJiang** [comment]
可以用一个项目中的自定义类继承三方库的类，然后在 xml 里使用自定义的？

**Comment by Petterpx** [comment]
> 可以用一个项目中的自定义类继承三方库的类，然后在 xml 里使用自定义的？

虽然可以这样，但仍希望这种事情是由工具来处理。
