### ISSUE TITLE
DexArchiveMergerException throws when there are multiple layout files with the same name.

### ISSUE THREAD

**Issue by zhangzhenxi** [kanyun-inc/Kace#32]
# Background

ProjectXXX has an Application module :app, and a library module :library :library2

:app depends on :library
:library depends on :library2

<img width="315" alt="image" src="https://user-images.githubusercontent.com/7889171/224538636-adec70b0-838b-4689-b272-a77dd374ffcb.png">

There is a `activity_base_list.xml` layout file in each module(including app)

# Env
```gradle
buildscript {
  repositories {
    google()
    mavenCentral()
  }
  dependencies {
    classpath 'com.kanyun.kace:kace-gradle-plugin:1.8.0-1.0.4'
  }
}

plugins {
  id 'com.android.application' version '7.4.1' apply false
  id 'com.android.library' version '7.4.1' apply false
  id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
}
```

# Issue
Build error because of dex merge failed
Multiple layout files with the same name will generate multiple class(with same name) in one package: `kotlinx.android.synthetic.main`

# Excpect
Should compile without any error like kotlin-extensions plugin.

**Comment by zhangzhenxi** [comment]
This issue is only happens when:
:app -> :lib1 -> :lib2
And all those modules all has a layout file with same name.


If there is no module :lib2(transive dependency layer less then three), then this issue won't happen.

**Comment by RicardoJiang** [comment]
Why do you have layouts with the same name in different modules? Only one will take effect in the end, right? Why not just keep one?

**Comment by zhangzhenxi** [comment]
These libraries are basic components such as ListPage VideoPlayer and so on, I can use these components in app with a customized ui layout when necessary.

**Comment by RicardoJiang** [comment]
Since the kace plugin is compatible with the kotlin-extensions plugin by generating source code, it cannot support duplicate classes. Maybe you can try to use blackList, so that the app module or lib1 module does not generate code

**Comment by zhangzhenxi** [comment]
Maybe I'll try some `kotlinx.android.synthetic.main.${package}` thing

**Comment by zhangzhenxi** [comment]
Here is an example:

<img width="3025" alt="image" src="https://user-images.githubusercontent.com/7889171/225230552-06252d9e-c262-426a-bf55-5fc32f4a7994.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/7889171/225230609-e03f4c9e-c5fb-455d-96be-b996280d72c7.png">
