### ISSUE TITLE
可以对外开放一个 clearFindViewByIdCache 接口吗，kotlin-android-extensions 是有的

### ISSUE THREAD

**Issue by jianghebj** [kanyun-inc/Kace#42]

**Comment by bennyhuo** [comment]
Kace 在 Activity 和 Fragment 销毁的时候会自动清理 Cache 的。kae 里面也是合成的字节码，想要调用需要反射吧？什么场景下会用到呢？

**Comment by jianghebj** [comment]
> 

动态 remove 掉一个 view ，再实例化一个新的 view 并 add 的场景下，旧的缓存应该会有问题。

**Comment by bennyhuo** [comment]
下版处理一下

**Comment by bennyhuo** [comment]
由于现在 Activity 、Fragment 都是编译时实现 AndroidExtensions 接口的，因此即便要添加 clearFindViewByIdCache 方法，也还是需要反射调用。由于使用场景较少，因此建议直接反射调用即可。
