### ISSUE TITLE
Failed resolution of: Lcom/kanyun/kace/AndroidExtensionsActivity$1;

### ISSUE THREAD

**Issue by mosentest** [kanyun-inc/Kace#52]
Failed resolution of: Lcom/kanyun/kace/AndroidExtensionsActivity$1;
生产包会报错

**Comment by bennyhuo** [comment]
请提供详细说明来帮助我们复现问题，包括使用的版本，agp版本，Kotlin版本等等。

当然，如果你希望你的问题尽快得到解决，最好提供可复现问题的demo工程，方便我们快速定位问题。

**Comment by bennyhuo** [comment]
请确认依赖中是否包含：     androidx.lifecycle:lifecycle-common 2.4.0 或者以上的版本。

**Comment by mosentest** [comment]
放弃不用了
