### ISSUE TITLE
kotlin升级1.9.20后会有这个报错 

### ISSUE THREAD

**Issue by MayDayzll** [kanyun-inc/Kace#55]
Execution failed for task ':app:kaptGenerateStubsDebugKotlin'.
> Could not resolve all files for configuration ':app:kotlinCompilerPluginClasspathDebug'.
   > Could not find kace-compiler-1.9.20-1.2.0.jar (com.kanyun.kace:kace-compiler:1.9.20-1.2.0).
     Searched in the following locations:
         https://maven.aliyun.com/repository/central/com/kanyun/kace/kace-compiler/1.9.20-1.2.0/kace-compiler-1.9.20-1.2.0.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by bennyhuo** [comment]
https://maven.aliyun.com/repository/central/com/kanyun/kace/kace-compiler/1.9.20-1.2.0/kace-compiler-1.9.20-1.2.0.jar
这个链接是可以下载的。建议检查网络环境重试。

如果 Gradle 持续报错，建议直接使用 mavenCentral，Kace 的所有构件都在这里可以查到：[https://search.maven.org/search?q=kace](https://search.maven.org/search?q=kace)。

如果无法使用 mavenCentral，也可以试试腾讯云的镜像：[https://mirrors.tencent.com/nexus/repository/maven-public/](https://mirrors.tencent.com/nexus/repository/maven-public/)，我这里使用腾讯云镜像是没有问题的。

**Comment by MayDayzll** [comment]
感谢 哥这么及时的回复 但是现在的问题是我确定从studio中看到aar引入进来的,其次我是阿里云镜像的并且我是有翻墙状态的现在还是提示这个错误,.gradle .idea的隐藏文件删除重新下载还是不行,但是我把kotlin版本改成1.8.20以及:kace-gradle-plugin:1.8.20-1.2.0的话就能正常的使用了就很怪


| |
赵龙龙
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | Benny ***@***.***> |
| 发送日期 | 2023年11月17日 16:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [kanyun-inc/Kace] kotlin升级1.9.20后会有这个报错 (Issue #55) |

Closed #55 as completed.

**Comment by bennyhuo** [comment]
阿里云镜像经常抽风，具体原因我也不是很清楚。我们之前也是用阿里云的，去年统一换成了腾讯云镜像，建议你试试看，修改方法也很简单：

如果你使用 groovy 的 Gradle 脚本，可以把 buildScript 里面的 repo 替换成：

```groovy
// 下载 gradle 插件用
maven { url "https://mirrors.tencent.com/nexus/repository/gradle-plugins/" }
// 代理了 mavenCentral 和 google 等常用仓库
maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
```

工程的依赖 repo 只添加这个即可：

```groovy
// 代理了 mavenCentral 和 google 等常用仓库
maven { url "https://mirrors.tencent.com/nexus/repository/maven-public" }
```

当然，如果网络环境允许，直接使用 mavenCentral 最简单。
