### ISSUE TITLE
打正式包报错：java.lang.IllegalAccessError: Interface androidx.lifecycle.g implemented by class com.kanyun.kace.KaceLifecycleObserver is inaccessible

### ISSUE THREAD

**Issue by xiaoanPan** [kanyun-inc/Kace#57]
FATAL EXCEPTION: main java.lang.IllegalAccessError: Interface androidx.lifecycle.g implemented by class com.kanyun.kace.KaceLifecycleObserver is inaccessible (declaration of 'com.kanyun.kace.KaceLifecycleObserver' appears in /data/app/~~YjuKoSvl_m5FX6jH7uXQcg==/com.nono.android-s4kgtMxsafLHXr4M8v3Nnw==/base.apk!classes2.dex)
                                                                                                    	at com.kanyun.kace.AndroidExtensionsFragment.<init>(SourceFile:4)
                                                                                                    	at com.kanyun.kace.d.h0(SourceFile:5)
                                                                                                    	at

**Comment by xiaoanPan** [comment]
版本：com.kanyun.kace:kace-gradle-plugin:1.9.20-1.2.0

**Comment by bennyhuo** [comment]
"androidx.lifecycle:lifecycle-common:2.4.0"

需要加一下依赖，这个后面我们在文档里面补充一下

**Comment by xiaoanPan** [comment]
![Snipaste_2023-12-29_09-47-39](https://github.com/kanyun-inc/Kace/assets/16420863/cc6788a3-31f8-4952-80bb-f86466cc689c)
感谢回复，但这个依赖我在看其他issue的时候已经加过了，问题还是一样的，因为arouter里面也有lifecycle-common，所以我指定了一下版本是2.4.0，问题是一样的。

**Comment by xiaoanPan** [comment]
另外，我检查过了包依赖，所有lifecycle-common的引用都已经是2.4.0，类似下面这张图：
![image](https://github.com/kanyun-inc/Kace/assets/16420863/f377dc26-5ad1-457d-b109-0d9a9785fa2a)

**Comment by bennyhuo** [comment]
能提供一个可以复现问题的最小 Demo，我们分析一下吗？

**Comment by xiaoanPan** [comment]
-keep class androidx.lifecycle.** { *; }
虽然不知道为什么会有混淆的问题，但是我加上这句混淆之后就ok了，感谢您对这个问题的关注。
