### ISSUE TITLE
可以支持一下Dialog嘛

### ISSUE THREAD

**Issue by TongmingWu** [kanyun-inc/Kace#6]
可以做一个支持Dialog的开关吗？因为考虑到旧项目其实用到Dialog的场景还是比较多的

**Comment by bennyhuo** [comment]
可以提供一下你的具体使用场景吗，我们评估一下

**Comment by TongmingWu** [comment]
主要是现有项目里边，DialogFragment和Dialog都有在用，把Dialog都迁移到DialogFragment成本会比较高

**Comment by TongmingWu** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/13725834/203713200-919d3bb9-3133-40c1-958f-68252f95c479.png">
我这边拉了插件的源码下来，稍微改了一下，不确定有没有其他问题
