### ISSUE TITLE
Dialog和RecycleView ViewHolder兼容问题

### ISSUE THREAD

**Issue by chy116449859** [kanyun-inc/Kace#60]
Dialog和RecycleView ViewHolder里面的布局没有做兼容，请问有没有方案处理？

**Comment by RicardoJiang** [comment]
目前支持 DialogFragment, Dialog 不支持且没有计划支持，如果有个别 Dialog 页面建议手动迁移。
RecyclerView 中的 ViewHolder 应该是支持通过类似 holder.itemView.tv_header_title.text = "首页" 的方法调用的
